PROJNAME=SARK100_SwrAnalyzer_BL
DEVICE=CY8C29466
BASEDEVICE=CY8C29000
PROJPATH=C:/work/RadioHam/psoc/SWRANA~1/prj/SARK10~1/SARK10~1/SARK10~1
PSOCDIR=C:/ARCHIV~1/Cypress/Common/CYPRES~3
INCLUDE_PATH=C:/ARCHIV~1/Cypress/Common/CYPRES~3/tools/include/CY8C29~1
CSRCS= bootloader.c buzzer.c calcs.c calibrate_reflectometer.c dds.c display.c glb_data.c keypad.c main.c measure.c msg_eng.c pclink.c sleep_timer.c storage.c util.c
LIBCSRCS=
ASMSRCS= bootloaderconfig.asm flashapi.asm
LIBASMSRCS= adcinc12.asm adcinc12int.asm amux4_adc.asm e2prom.asm lcd.asm pga_adc.asm pga_dds_1.asm pga_dds_2.asm psocconfig.asm psocconfigtbl.asm pwm8_buzz.asm pwm8_buzzint.asm timer16_delay.asm timer16_delayint.asm uart.asm uartint.asm uartplus.asm
OBJECT_SOURCES= bootloader.c bootloaderconfig.asm buzzer.c calcs.c calibrate_reflectometer.c dds.c display.c flashapi.asm glb_data.c keypad.c main.c measure.c msg_eng.c pclink.c sleep_timer.c storage.c util.c
FILLVALUE=0x30
LASTROM=0x7fff
LASTRAM=0x7ff
LAST_DATARAM=0x6ff
CODECOMPRESSOR=
MORE_CFLAGS=-Wf-Osize -Wf-LMM8 -D_LMM
RELSTART=0x1a0
CDEFINES=
LIBS=
UMLIBS=
LIB_PATH=
ENABLE_ALIGN_SHIFT=0
LMM=1
SYS_INC_CONTENTS:=SYSTEM_STACK_PAGE:_equ_7 SYSTEM_STACK_BASE_ADDR:_equ_0h SYSTEM_LARGE_MEMORY_MODEL:_equ_1 SYSTEM_SMALL_MEMORY_MODEL:_equ_0 IMAGECRAFT:_equ_1 HITECH:_equ_2 TOOLCHAIN:_equ_IMAGECRAFT 
SYSTEM_TOOLS=1
CSFLOW=
CONFIG_NAMES=sark100_swranalyzer_bl 
