; Generated by PSoC Designer 
;
include "m8c.inc"
;  Personalization tables 
export LoadConfigTBL_sark100_swranalyzer_bl_Bank1
export LoadConfigTBL_sark100_swranalyzer_bl_Bank0
export LoadConfigTBL_sark100_swranalyzer_bl_Ordered
AREA lit(rom, rel)
LoadConfigTBL_sark100_swranalyzer_bl_Bank0:
;  Instance name ADCINC12, User Module ADCINC12
;       Instance name ADCINC12, Block Name ADC(ASC10)
	db		80h, 90h		;ADCINC12_AtoDcr0(ASC10CR0)
	db		81h, 00h		;ADCINC12_AtoDcr1(ASC10CR1)
	db		82h, 60h		;ADCINC12_AtoDcr2(ASC10CR2)
	db		83h, f0h		;ADCINC12_AtoDcr3(ASC10CR3)
;       Instance name ADCINC12, Block Name CNT(DBB01)
	db		27h, 00h		;ADCINC12_CounterCR0(DBB01CR0)
	db		25h, 00h		;ADCINC12_CounterDR1(DBB01DR1)
	db		26h, 00h		;ADCINC12_CounterDR2(DBB01DR2)
;       Instance name ADCINC12, Block Name TMR(DBB00)
	db		23h, 00h		;ADCINC12_TimerCR0(DBB00CR0)
	db		21h, 00h		;ADCINC12_TimerDR1(DBB00DR1)
	db		22h, 00h		;ADCINC12_TimerDR2(DBB00DR2)
;  Instance name AMUX4_ADC, User Module AMUX4
;  Instance name E2PROM, User Module E2PROM
;  Instance name LCD, User Module LCD
;  Instance name PGA_ADC, User Module PGA
;       Instance name PGA_ADC, Block Name GAIN(ACB00)
	db		71h, feh		;PGA_ADC_GAIN_CR0(ACB00CR0)
	db		72h, 21h		;PGA_ADC_GAIN_CR1(ACB00CR1)
	db		73h, 20h		;PGA_ADC_GAIN_CR2(ACB00CR2)
	db		70h, 00h		;PGA_ADC_GAIN_CR3(ACB00CR3)
;  Instance name PGA_DDS_1, User Module PGA
;       Instance name PGA_DDS_1, Block Name GAIN(ACB03)
	db		7dh, 66h		;PGA_DDS_1_GAIN_CR0(ACB03CR0)
	db		7eh, a2h		;PGA_DDS_1_GAIN_CR1(ACB03CR1)
	db		7fh, 20h		;PGA_DDS_1_GAIN_CR2(ACB03CR2)
	db		7ch, 00h		;PGA_DDS_1_GAIN_CR3(ACB03CR3)
;  Instance name PGA_DDS_2, User Module PGA
;       Instance name PGA_DDS_2, Block Name GAIN(ACB02)
	db		79h, 76h		;PGA_DDS_2_GAIN_CR0(ACB02CR0)
	db		7ah, 23h		;PGA_DDS_2_GAIN_CR1(ACB02CR1)
	db		7bh, 20h		;PGA_DDS_2_GAIN_CR2(ACB02CR2)
	db		78h, 00h		;PGA_DDS_2_GAIN_CR3(ACB02CR3)
;  Instance name PWM8_BUZZ, User Module PWM8
;       Instance name PWM8_BUZZ, Block Name PWM8(DBB11)
	db		37h, 00h		;PWM8_BUZZ_CONTROL_REG(DBB11CR0)
	db		35h, 00h		;PWM8_BUZZ_PERIOD_REG(DBB11DR1)
	db		36h, 00h		;PWM8_BUZZ_COMPARE_REG(DBB11DR2)
;  Instance name Timer16_Delay, User Module Timer16
;       Instance name Timer16_Delay, Block Name TIMER16_LSB(DCB03)
	db		2fh, 00h		;Timer16_Delay_CONTROL_LSB_REG(DCB03CR0)
	db		2dh, 00h		;Timer16_Delay_PERIOD_LSB_REG(DCB03DR1)
	db		2eh, 00h		;Timer16_Delay_COMPARE_LSB_REG(DCB03DR2)
;       Instance name Timer16_Delay, Block Name TIMER16_MSB(DBB10)
	db		33h, 04h		;Timer16_Delay_CONTROL_MSB_REG(DBB10CR0)
	db		31h, 00h		;Timer16_Delay_PERIOD_MSB_REG(DBB10DR1)
	db		32h, 00h		;Timer16_Delay_COMPARE_MSB_REG(DBB10DR2)
;  Instance name UART, User Module UART
;       Instance name UART, Block Name RX(DCB23)
	db		4fh, 00h		;UART_RX_CONTROL_REG(DCB23CR0)
	db		4dh, 00h		;UART_(DCB23DR1)
	db		4eh, 00h		;UART_RX_BUFFER_REG (DCB23DR2)
;       Instance name UART, Block Name TX(DCB22)
	db		4bh, 00h		;UART_TX_CONTROL_REG(DCB22CR0)
	db		49h, 00h		;UART_TX_BUFFER_REG (DCB22DR1)
	db		4ah, 00h		;UART_(DCB22DR2)
;  Global Register values Bank 0
	db		60h, 28h		; AnalogColumnInputSelect register (AMX_IN)
	db		66h, 00h		; AnalogComparatorControl1 register (CMP_CR1)
	db		63h, 57h		; AnalogReferenceControl register (ARF_CR)
	db		65h, 00h		; AnalogSyncControl register (ASY_CR)
	db		e6h, 00h		; DecimatorControl_0 register (DEC_CR0)
	db		e7h, 00h		; DecimatorControl_1 register (DEC_CR1)
	db		d6h, 00h		; I2CConfig register (I2C_CFG)
	db		b0h, 00h		; Row_0_InputMux register (RDI0RI)
	db		b1h, 00h		; Row_0_InputSync register (RDI0SYN)
	db		b2h, 00h		; Row_0_LogicInputAMux register (RDI0IS)
	db		b3h, 33h		; Row_0_LogicSelect_0 register (RDI0LT0)
	db		b4h, 33h		; Row_0_LogicSelect_1 register (RDI0LT1)
	db		b5h, 00h		; Row_0_OutputDrive_0 register (RDI0SRO0)
	db		b6h, 00h		; Row_0_OutputDrive_1 register (RDI0SRO1)
	db		b8h, 55h		; Row_1_InputMux register (RDI1RI)
	db		b9h, 00h		; Row_1_InputSync register (RDI1SYN)
	db		bah, 10h		; Row_1_LogicInputAMux register (RDI1IS)
	db		bbh, 33h		; Row_1_LogicSelect_0 register (RDI1LT0)
	db		bch, 33h		; Row_1_LogicSelect_1 register (RDI1LT1)
	db		bdh, 01h		; Row_1_OutputDrive_0 register (RDI1SRO0)
	db		beh, 00h		; Row_1_OutputDrive_1 register (RDI1SRO1)
	db		c0h, 80h		; Row_2_InputMux register (RDI2RI)
	db		c1h, 00h		; Row_2_InputSync register (RDI2SYN)
	db		c2h, 20h		; Row_2_LogicInputAMux register (RDI2IS)
	db		c3h, 33h		; Row_2_LogicSelect_0 register (RDI2LT0)
	db		c4h, 33h		; Row_2_LogicSelect_1 register (RDI3LT1)
	db		c5h, 02h		; Row_2_OutputDrive_0 register (RDI2SRO0)
	db		c6h, 00h		; Row_2_OutputDrive_1 register (RDI2SRO1)
	db		c8h, 55h		; Row_3_InputMux register (RDI3RI)
	db		c9h, 00h		; Row_3_InputSync register (RDI3SYN)
	db		cah, 30h		; Row_3_LogicInputAMux register (RDI3IS)
	db		cbh, 33h		; Row_3_LogicSelect_0 register (RDI3LT0)
	db		cch, 33h		; Row_3_LogicSelect_1 register (RDI3LT1)
	db		cdh, 00h		; Row_3_OutputDrive_0 register (RDI3SRO0)
	db		ceh, 00h		; Row_3_OutputDrive_1 register (RDI3SRO1)
	db		6ch, 00h		; TMP_DR0 register (TMP_DR0)
	db		6dh, 00h		; TMP_DR1 register (TMP_DR1)
	db		6eh, 00h		; TMP_DR2 register (TMP_DR2)
	db		6fh, 00h		; TMP_DR3 register (TMP_DR3)
	db		ffh
LoadConfigTBL_sark100_swranalyzer_bl_Bank1:
;  Instance name ADCINC12, User Module ADCINC12
;       Instance name ADCINC12, Block Name ADC(ASC10)
;       Instance name ADCINC12, Block Name CNT(DBB01)
	db		24h, 21h		;ADCINC12_CounterFN(DBB01FN)
	db		25h, 45h		;ADCINC12_CounterSL(DBB01IN)
	db		26h, 40h		;ADCINC12_CounterOS(DBB01OU)
;       Instance name ADCINC12, Block Name TMR(DBB00)
	db		20h, 20h		;ADCINC12_TimerFN(DBB00FN)
	db		21h, 15h		;ADCINC12_TimerSL(DBB00IN)
	db		22h, 40h		;ADCINC12_TimerOS(DBB00OU)
;  Instance name AMUX4_ADC, User Module AMUX4
;  Instance name E2PROM, User Module E2PROM
;  Instance name LCD, User Module LCD
;  Instance name PGA_ADC, User Module PGA
;       Instance name PGA_ADC, Block Name GAIN(ACB00)
;  Instance name PGA_DDS_1, User Module PGA
;       Instance name PGA_DDS_1, Block Name GAIN(ACB03)
;  Instance name PGA_DDS_2, User Module PGA
;       Instance name PGA_DDS_2, Block Name GAIN(ACB02)
;  Instance name PWM8_BUZZ, User Module PWM8
;       Instance name PWM8_BUZZ, Block Name PWM8(DBB11)
	db		34h, 21h		;PWM8_BUZZ_FUNC_REG(DBB11FN)
	db		35h, 17h		;PWM8_BUZZ_INPUT_REG(DBB11IN)
	db		36h, 04h		;PWM8_BUZZ_OUTPUT_REG(DBB11OU)
;  Instance name Timer16_Delay, User Module Timer16
;       Instance name Timer16_Delay, Block Name TIMER16_LSB(DCB03)
	db		2ch, 00h		;Timer16_Delay_FUNC_LSB_REG(DCB03FN)
	db		2dh, 07h		;Timer16_Delay_INPUT_LSB_REG(DCB03IN)
	db		2eh, 00h		;Timer16_Delay_OUTPUT_LSB_REG(DCB03OU)
;       Instance name Timer16_Delay, Block Name TIMER16_MSB(DBB10)
	db		30h, 20h		;Timer16_Delay_FUNC_MSB_REG(DBB10FN)
	db		31h, 37h		;Timer16_Delay_INPUT_MSB_REG(DBB10IN)
	db		32h, 00h		;Timer16_Delay_OUTPUT_MSB_REG(DBB10OU)
;  Instance name UART, User Module UART
;       Instance name UART, Block Name RX(DCB23)
	db		4ch, 05h		;UART_RX_FUNC_REG   (DCB23FN)
	db		4dh, f1h		;UART_RX_INPUT_REG  (DCB23IN)
	db		4eh, 40h		;UART_RX_OUTPUT_REG (DCB23OU)
;       Instance name UART, Block Name TX(DCB22)
	db		48h, 1dh		;UART_TX_FUNC_REG   (DCB22FN)
	db		49h, 01h		;UART_TX_INPUT_REG  (DCB22IN)
	db		4ah, 44h		;UART_TX_OUTPUT_REG (DCB22OU)
;  Global Register values Bank 1
	db		61h, 00h		; AnalogClockSelect1 register (CLK_CR1)
	db		69h, 00h		; AnalogClockSelect2 register (CLK_CR2)
	db		60h, 00h		; AnalogColumnClockSelect register (CLK_CR0)
	db		62h, 04h		; AnalogIOControl_0 register (ABF_CR0)
	db		67h, 33h		; AnalogLUTControl0 register (ALT_CR0)
	db		68h, 33h		; AnalogLUTControl1 register (ALT_CR1)
	db		63h, 00h		; AnalogModulatorControl_0 register (AMD_CR0)
	db		66h, 00h		; AnalogModulatorControl_1 register (AMD_CR1)
	db		d1h, 00h		; GlobalDigitalInterconnect_Drive_Even_Input register (GDI_E_IN)
	db		d3h, 00h		; GlobalDigitalInterconnect_Drive_Even_Output register (GDI_E_OU)
	db		d0h, 00h		; GlobalDigitalInterconnect_Drive_Odd_Input register (GDI_O_IN)
	db		d2h, 00h		; GlobalDigitalInterconnect_Drive_Odd_Output register (GDI_O_OU)
	db		e1h, 7fh		; OscillatorControl_1 register (OSC_CR1)
	db		e2h, 00h		; OscillatorControl_2 register (OSC_CR2)
	db		dfh, 33h		; OscillatorControl_3 register (OSC_CR3)
	db		deh, 00h		; OscillatorControl_4 register (OSC_CR4)
	db		ddh, 00h		; OscillatorGlobalBusEnableControl register (OSC_GO_EN)
	db		e7h, 00h		; Type2Decimator_Control register (DEC_CR2)
	db		ffh
LoadConfigTBL_sark100_swranalyzer_bl_Ordered:
;  Ordered Global Register values
	M8C_SetBank1
	mov	reg[00h], 51h		; Port_0_DriveMode_0 register (PRT0DM0)
	mov	reg[01h], aeh		; Port_0_DriveMode_1 register (PRT0DM1)
	M8C_SetBank0
	mov	reg[03h], aeh		; Port_0_DriveMode_2 register (PRT0DM2)
	mov	reg[02h], 11h		; Port_0_GlobalSelect register (PRT0GS)
	M8C_SetBank1
	mov	reg[02h], 00h		; Port_0_IntCtrl_0 register (PRT0IC0)
	mov	reg[03h], 00h		; Port_0_IntCtrl_1 register (PRT0IC1)
	M8C_SetBank0
	mov	reg[01h], 00h		; Port_0_IntEn register (PRT0IE)
	M8C_SetBank1
	mov	reg[04h], f4h		; Port_1_DriveMode_0 register (PRT1DM0)
	mov	reg[05h], 0bh		; Port_1_DriveMode_1 register (PRT1DM1)
	M8C_SetBank0
	mov	reg[07h], 00h		; Port_1_DriveMode_2 register (PRT1DM2)
	mov	reg[06h], 08h		; Port_1_GlobalSelect register (PRT1GS)
	M8C_SetBank1
	mov	reg[06h], 00h		; Port_1_IntCtrl_0 register (PRT1IC0)
	mov	reg[07h], 00h		; Port_1_IntCtrl_1 register (PRT1IC1)
	M8C_SetBank0
	mov	reg[05h], 00h		; Port_1_IntEn register (PRT1IE)
	M8C_SetBank1
	mov	reg[08h], ffh		; Port_2_DriveMode_0 register (PRT2DM0)
	mov	reg[09h], 00h		; Port_2_DriveMode_1 register (PRT2DM1)
	M8C_SetBank0
	mov	reg[0bh], 00h		; Port_2_DriveMode_2 register (PRT2DM2)
	mov	reg[0ah], 00h		; Port_2_GlobalSelect register (PRT2GS)
	M8C_SetBank1
	mov	reg[0ah], 00h		; Port_2_IntCtrl_0 register (PRT2IC0)
	mov	reg[0bh], 00h		; Port_2_IntCtrl_1 register (PRT2IC1)
	M8C_SetBank0
	mov	reg[09h], 00h		; Port_2_IntEn register (PRT2IE)
	M8C_SetBank1
	mov	reg[0ch], 00h		; Port_3_DriveMode_0 register (PRT3DM0)
	mov	reg[0dh], 00h		; Port_3_DriveMode_1 register (PRT3DM1)
	M8C_SetBank0
	mov	reg[0fh], 00h		; Port_3_DriveMode_2 register (PRT3DM2)
	mov	reg[0eh], 00h		; Port_3_GlobalSelect register (PRT3GS)
	M8C_SetBank1
	mov	reg[0eh], 00h		; Port_3_IntCtrl_0 register (PRT3IC0)
	mov	reg[0fh], 00h		; Port_3_IntCtrl_1 register (PRT3IC1)
	M8C_SetBank0
	mov	reg[0dh], 00h		; Port_3_IntEn register (PRT3IE)
	M8C_SetBank1
	mov	reg[10h], 00h		; Port_4_DriveMode_0 register (PRT4DM0)
	mov	reg[11h], 00h		; Port_4_DriveMode_1 register (PRT4DM1)
	M8C_SetBank0
	mov	reg[13h], 00h		; Port_4_DriveMode_2 register (PRT4DM2)
	mov	reg[12h], 00h		; Port_4_GlobalSelect register (PRT4GS)
	M8C_SetBank1
	mov	reg[12h], 00h		; Port_4_IntCtrl_0 register (PRT4IC0)
	mov	reg[13h], 00h		; Port_4_IntCtrl_1 register (PRT4IC1)
	M8C_SetBank0
	mov	reg[11h], 00h		; Port_4_IntEn register (PRT4IE)
	M8C_SetBank1
	mov	reg[14h], 00h		; Port_5_DriveMode_0 register (PRT5DM0)
	mov	reg[15h], 00h		; Port_5_DriveMode_1 register (PRT5DM1)
	M8C_SetBank0
	mov	reg[17h], 00h		; Port_5_DriveMode_2 register (PRT5DM2)
	mov	reg[16h], 00h		; Port_5_GlobalSelect register (PRT5GS)
	M8C_SetBank1
	mov	reg[16h], 00h		; Port_5_IntCtrl_0 register (PRT5IC0)
	mov	reg[17h], 00h		; Port_5_IntCtrl_1 register (PRT5IC1)
	M8C_SetBank0
	mov	reg[15h], 00h		; Port_5_IntEn register (PRT5IE)
	M8C_SetBank1
	mov	reg[18h], 00h		; Port_6_DriveMode_0 register (PRT6DM0)
	mov	reg[19h], 00h		; Port_6_DriveMode_1 register (PRT6DM1)
	M8C_SetBank0
	mov	reg[1bh], 00h		; Port_6_DriveMode_2 register (PRT6DM2)
	mov	reg[1ah], 00h		; Port_6_GlobalSelect register (PRT6GS)
	M8C_SetBank1
	mov	reg[1ah], 00h		; Port_6_IntCtrl_0 register (PRT6IC0)
	mov	reg[1bh], 00h		; Port_6_IntCtrl_1 register (PRT6IC1)
	M8C_SetBank0
	mov	reg[19h], 00h		; Port_6_IntEn register (PRT6IE)
	M8C_SetBank1
	mov	reg[1ch], 00h		; Port_7_DriveMode_0 register (PRT7DM0)
	mov	reg[1dh], 00h		; Port_7_DriveMode_1 register (PRT7DM1)
	M8C_SetBank0
	mov	reg[1fh], 00h		; Port_7_DriveMode_2 register (PRT7DM2)
	mov	reg[1eh], 00h		; Port_7_GlobalSelect register (PRT7GS)
	M8C_SetBank1
	mov	reg[1eh], 00h		; Port_7_IntCtrl_0 register (PRT7IC0)
	mov	reg[1fh], 00h		; Port_7_IntCtrl_1 register (PRT7IC1)
	M8C_SetBank0
	mov	reg[1dh], 00h		; Port_7_IntEn register (PRT7IE)
	ret


; PSoC Configuration file trailer PsocConfig.asm
