/******************************************************************************
*  Generated by PSoC Designer 
******************************************************************************/
#include "ADCINC12.h"
#include "AMUX4_ADC.h"
#include "E2PROM.h"
#include "LCD.h"
#include "PGA_ADC.h"
#include "PGA_DDS_1.h"
#include "PGA_DDS_2.h"
#include "PWM8_BUZZ.h"
#include "Timer16_Delay.h"
#include "UART.h"
