//*****************************************************************************
//*****************************************************************************
//  FILENAME: Timer16_Delay.h
//   Version: 2.6, Updated on 2009/6/24 at 12:17:24
//  Generated by PSoC Designer 
//
//  DESCRIPTION: Timer16 User Module C Language interface file
//               for the 22/24/27/29xxx PSoC family of devices
//-----------------------------------------------------------------------------
//  Copyright (c) Cypress MicroSystems 2000-2004. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************

#include <m8c.h>

#pragma fastcall16 Timer16_Delay_EnableInt
#pragma fastcall16 Timer16_Delay_DisableInt
#pragma fastcall16 Timer16_Delay_Start
#pragma fastcall16 Timer16_Delay_Stop
#pragma fastcall16 Timer16_Delay_wReadTimer                // Read  DR0
#pragma fastcall16 Timer16_Delay_wReadTimerSaveCV          // Read  DR0      
#pragma fastcall16 Timer16_Delay_WritePeriod               // Write DR1
#pragma fastcall16 Timer16_Delay_wReadCompareValue         // Read  DR2
#pragma fastcall16 Timer16_Delay_WriteCompareValue         // Write DR2

// The following symbols are deprecated.
// They may be omitted in future releases
//
#pragma fastcall16 wTimer16_Delay_ReadCounter              // Read  DR0 "Obsolete"
#pragma fastcall16 wTimer16_Delay_CaptureCounter           // Read  DR0 "Obsolete"
#pragma fastcall16 wTimer16_Delay_ReadTimer                // Read  DR0 (Deprecated)
#pragma fastcall16 wTimer16_Delay_ReadTimerSaveCV          // Read  DR0 (Deprecated)
#pragma fastcall16 wTimer16_Delay_ReadCompareValue         // Read  DR2 (Deprecated)


//-------------------------------------------------
// Prototypes of the Timer16_Delay API.
//-------------------------------------------------

extern void Timer16_Delay_EnableInt(void);                           // Proxy 1
extern void Timer16_Delay_DisableInt(void);                          // Proxy 1
extern void Timer16_Delay_Start(void);                               // Proxy 1
extern void Timer16_Delay_Stop(void);                                // Proxy 1
extern WORD Timer16_Delay_wReadTimer(void);                          // Proxy 1
extern WORD Timer16_Delay_wReadTimerSaveCV(void);                    // Proxy 2
extern void Timer16_Delay_WritePeriod(WORD wPeriod);                 // Proxy 1
extern WORD Timer16_Delay_wReadCompareValue(void);                   // Proxy 1
extern void Timer16_Delay_WriteCompareValue(WORD wCompareValue);     // Proxy 1

// The following functions are deprecated.
// They may be omitted in future releases
//
extern WORD wTimer16_Delay_ReadCompareValue(void);       // Deprecated
extern WORD wTimer16_Delay_ReadTimerSaveCV(void);        // Deprecated
extern WORD wTimer16_Delay_ReadCounter(void);            // Obsolete
extern WORD wTimer16_Delay_ReadTimer(void);              // Deprecated
extern WORD wTimer16_Delay_CaptureCounter(void);         // Obsolete


//--------------------------------------------------
// Constants for Timer16_Delay API's.
//--------------------------------------------------

#define Timer16_Delay_CONTROL_REG_START_BIT    ( 0x01 )
#define Timer16_Delay_INT_REG_ADDR             ( 0x0e1 )
#define Timer16_Delay_INT_MASK                 ( 0x10 )


//--------------------------------------------------
// Constants for Timer16_Delay user defined values
//--------------------------------------------------

#define Timer16_Delay_PERIOD                   ( 0x0 )
#define Timer16_Delay_COMPARE_VALUE            ( 0x0 )


//-------------------------------------------------
// Register Addresses for Timer16_Delay
//-------------------------------------------------

#pragma ioport  Timer16_Delay_COUNTER_LSB_REG:  0x02c      //Count register LSB
BYTE            Timer16_Delay_COUNTER_LSB_REG;
#pragma ioport  Timer16_Delay_COUNTER_MSB_REG:  0x030      //Count register MSB
BYTE            Timer16_Delay_COUNTER_MSB_REG;
#pragma ioport  Timer16_Delay_PERIOD_LSB_REG:   0x02d      //Period register LSB
BYTE            Timer16_Delay_PERIOD_LSB_REG;
#pragma ioport  Timer16_Delay_PERIOD_MSB_REG:   0x031      //Period register MSB
BYTE            Timer16_Delay_PERIOD_MSB_REG;
#pragma ioport  Timer16_Delay_COMPARE_LSB_REG:  0x02e      //Compare register LSB
BYTE            Timer16_Delay_COMPARE_LSB_REG;
#pragma ioport  Timer16_Delay_COMPARE_MSB_REG:  0x032      //Compare register MSB
BYTE            Timer16_Delay_COMPARE_MSB_REG;
#pragma ioport  Timer16_Delay_CONTROL_LSB_REG:  0x02f      //Control register LSB
BYTE            Timer16_Delay_CONTROL_LSB_REG;
#pragma ioport  Timer16_Delay_CONTROL_MSB_REG:  0x033      //Control register MSB
BYTE            Timer16_Delay_CONTROL_MSB_REG;
#pragma ioport  Timer16_Delay_FUNC_LSB_REG: 0x12c          //Function register LSB
BYTE            Timer16_Delay_FUNC_LSB_REG;
#pragma ioport  Timer16_Delay_FUNC_MSB_REG: 0x130          //Function register MSB
BYTE            Timer16_Delay_FUNC_MSB_REG;
#pragma ioport  Timer16_Delay_INPUT_LSB_REG:    0x12d      //Input register LSB
BYTE            Timer16_Delay_INPUT_LSB_REG;
#pragma ioport  Timer16_Delay_INPUT_MSB_REG:    0x131      //Input register MSB
BYTE            Timer16_Delay_INPUT_MSB_REG;
#pragma ioport  Timer16_Delay_OUTPUT_LSB_REG:   0x12e      //Output register LSB
BYTE            Timer16_Delay_OUTPUT_LSB_REG;
#pragma ioport  Timer16_Delay_OUTPUT_MSB_REG:   0x132      //Output register MSB
BYTE            Timer16_Delay_OUTPUT_MSB_REG;
#pragma ioport  Timer16_Delay_INT_REG:       0x0e1         //Interrupt Mask Register
BYTE            Timer16_Delay_INT_REG;


//-------------------------------------------------
// Timer16_Delay Macro 'Functions'
//-------------------------------------------------

#define Timer16_Delay_Start_M \
   ( Timer16_Delay_CONTROL_LSB_REG |=  Timer16_Delay_CONTROL_REG_START_BIT )

#define Timer16_Delay_Stop_M  \
   ( Timer16_Delay_CONTROL_LSB_REG &= ~Timer16_Delay_CONTROL_REG_START_BIT )

#define Timer16_Delay_EnableInt_M   \
   M8C_EnableIntMask(  Timer16_Delay_INT_REG, Timer16_Delay_INT_MASK )

#define Timer16_Delay_DisableInt_M  \
   M8C_DisableIntMask( Timer16_Delay_INT_REG, Timer16_Delay_INT_MASK )


// end of file Timer16_Delay.h


